import React from 'react'; // Add this line

import Head from 'next/head';
import { LinkArrow } from '../components/Icons';
import Layout from '../components/Layout';
import AnimatedText from '../components/AnimatedText';
import profileImage from '../../public/vercel.svg';
import Image from 'next/image';
import Link from 'next/link';

export default function Home() {
  return (
    <>
      <Head>
        <title>Happy Yadav Portfolio</title>
        <meta name="description" content="Generated by create next app" />
       
      </Head>
      
      <main className='flex items-center text-dark w-full min-h-screen'>
      <Layout className='pt-0'>
        <div className="flex items-center justify-between w-full">
        <div className='w-1/2'>
          <Image src={profileImage} alt="happy yadav" className='w-1/2 h-auto' width={100} height={100} />
        </div>
        <div className='w-1/2 flex flex-col items-center self-center'> 
          <AnimatedText text="Turning &nbsp;Vision &nbsp;Into &nbsp;Reality &nbsp; With &nbsp;Code &nbsp;And &nbsp;Design." className='!text-4xl !text-left' />
            <p className='my-4 text-base font-medium'>
            As a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications. 
Explore my latest projects and articles, showcasing my expertise in React.js and web development.

            </p>
            <div className='flex items-center self-start mt-2'>
              <Link href="/resume.pdf" target={"_blank"}
              className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover: border-dark"
              download={true}
              >Resume <LinkArrow className={"w-6"}></LinkArrow></Link>
              <Link href="mailto:happy.hy0017@gmail.com" target={"_blank"}
              className="ml-4 text-lg font-medium capitalize text-dark underline"
              >Contact</Link>
            </div>
          
        </div>

        </div>
      </Layout>
      </main>
    </>
  )
}
